### ISSUE TITLE
Error in strokeWidth of MessageView

### ISSUE THREAD

**Issue by Nikhilkumar25** [technojam/AndroidCustomView#27]
### Before reporting an issue I am agreeing to the points below
- [ ] I'm running my app on SDK level > 21.
- [ ] Target SDK version on my machine is 28.
- [ ] I haven't altered the default Gradle configuration for the app.

### Description
The StrokeWidth attribute in MessageBox is not accepting 5dp or any value 

### Steps to reproduce the behavior:
1. Go to 'run the application directly '
2. Click on ' Build'
3. Scroll down to 'here you will see the cause of error'
4. See an error

### Expected behavior
Run perfectly and the message box stroke width should be 5dp
.

## Platform Info
 - Device: [Samsung A30]
 - OS: [Android 10]

**Additional context**

**Comment by danishjamal104** [comment]
@Nikhilkumar25 please make sure to u agree to all the points mentioned in the checklist of issue template.
