### ISSUE TITLE
AnalogClock View

### ISSUE THREAD

**Issue by noman2002** [technojam/AndroidCustomView#5]
**AnalogClockView**

**Implement a basic analog clock view**

**Comment by danishjamal104** [comment]
can u explain 1-2 line about clock view.

**Comment by noman2002** [comment]
Basically it will just be a simple analog clock.

**Comment by abhi114** [comment]
can i work on this issue ??

**Comment by noman2002** [comment]
ya sure @abhi114

**Comment by Algure** [comment]
I'd like to work on a digital clockview
