### ISSUE TITLE
[BUG] ProgressView text alignment

### ISSUE THREAD

**Issue by danishjamal104** [technojam/AndroidCustomView#8]
### Before reporting an issue I am agreeing to the points below
- [x] I'm running my app on SDK level > 21.
- [x] Target SDK version on my machine is 28.
- [x] I haven't altered the default Gradle configuration for the app.

### Description
The text in the progress view is not aligned and scalable. The main issue is with the reference from which it is drawn. It is required to be positioned correctly.

### Steps to reproduce the behavior:
1. Go to [activity_main.xml](https://github.com/technojam/AndroidCustomView/blob/master/app/src/main/res/layout/activity_main.xml) line number 14.
2. Alter the layout_width and layout_height to see how text behaves
3. There is no app crash.

### Expected behavior
Centered between the circle independent of layout_width and layout_height maintaining the aspect ratio.

### Screenshot
<img src="https://raw.githubusercontent.com/technojam/AndroidCustomView/master/screenshots/ss_1.png"
width="150" height="275">

### Platform Info
 - Device: [Pixel XL 2 emulator]
 - OS: [android oreo]

**Comment by noman2002** [comment]
I'd like to work on it . Please assign it to me. @danishjamal104

**Comment by rahullli** [comment]
I would like to work on this issue .

**Comment by altruisticdream** [comment]
I would to work on this issue, please assign it to me.

**Comment by rahullli** [comment]
I have fixed the issue , please check the PR and merge it .
